import java.io.*;
import java.io.IOException;
import java.nio.file.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class CowPage extends javax.swing.JFrame {
Data Data = new Data();
private String order1,order2,order3;
//SET STOCKS LINE!
private int stocksline1 = 4, stocksline2 = 5,stocksline3 = 6;
private String stocks1, stocks2, stocks3;
private int priceline1 = 14, priceline2 = 15, priceline3 = 16;
private String price1, price2, price3;
    /**
     * Creates new form MainPage
     */
    public CowPage() {
        
        initComponents();
        
        //@@@MODIFY IF NECESARRY@@@
        //------Automatically Set Label to Intended Nunmbers -----
        
        
        try {
            
            stocks1 = Integer.toString(Data.GetData(stocksline1));
            stocks2 = Integer.toString(Data.GetData(stocksline2));
            stocks3 = Integer.toString(Data.GetData(stocksline3));
            price1 = Integer.toString(Data.GetData(priceline1));
            price2 = Integer.toString(Data.GetData(priceline2));
            price3 = Integer.toString(Data.GetData(priceline3));
            jLabel_PigStockLeft1.setText("Stocks Left: " + stocks1);
            jLabel_PigStockLeft2.setText("Stocks Left: " + stocks2);
            jLabel_PigStockLeft3.setText("Stocks Left: " + stocks3);
            jLabel_PigPrice1.setText("Price: " + price1);
            jLabel_PigPrice2.setText("Price: " + price2);
            jLabel_PigPrice3.setText("Price: " + price3);
            tlCurrentlyInCart.setText("Currently in Cart: " + Integer.toString(Data.CurrentlyInCart()));
            tlMoney.setText("Money: " + Data.GetUserMoney());
        } catch (IOException e) {}
        
        //------Automatically Set Label to Intended Nunmbers -----
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Cart = new javax.swing.JPanel();
        tlCurrentlyInCart = new javax.swing.JLabel();
        jPanel_Pig = new javax.swing.JPanel();
        jLabel_Image_Pig = new javax.swing.JLabel();
        Final_PigParts1 = new javax.swing.JLabel();
        jLabel_PigPrice1 = new javax.swing.JLabel();
        jLabel_PigStockLeft1 = new javax.swing.JLabel();
        jButton_Pig1 = new javax.swing.JButton();
        Final_PanelPig = new javax.swing.JPanel();
        Final_AmountOrder = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton_MainPage = new javax.swing.JButton();
        jPanel_Pig1 = new javax.swing.JPanel();
        jLabel_Image_Pig1 = new javax.swing.JLabel();
        Final_PigParts3 = new javax.swing.JLabel();
        jLabel_PigPrice3 = new javax.swing.JLabel();
        jLabel_PigStockLeft3 = new javax.swing.JLabel();
        jButton_Pig3 = new javax.swing.JButton();
        Final_PanelPig1 = new javax.swing.JPanel();
        Final_AmountOrder1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel_Pig2 = new javax.swing.JPanel();
        jLabel_Image_Pig2 = new javax.swing.JLabel();
        Final_PigParts2 = new javax.swing.JLabel();
        jLabel_PigPrice2 = new javax.swing.JLabel();
        jLabel_PigStockLeft2 = new javax.swing.JLabel();
        jButton_Pig2 = new javax.swing.JButton();
        Final_PanelPig2 = new javax.swing.JPanel();
        Final_AmountOrder2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel_Cart1 = new javax.swing.JPanel();
        tlMoney = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jPanel_Cart.setBackground(new java.awt.Color(102, 0, 51));
        jPanel_Cart.setAlignmentX(0.0F);
        jPanel_Cart.setAlignmentY(0.0F);

        tlCurrentlyInCart.setForeground(new java.awt.Color(255, 255, 255));
        tlCurrentlyInCart.setText("Currently in Cart: 00");

        javax.swing.GroupLayout jPanel_CartLayout = new javax.swing.GroupLayout(jPanel_Cart);
        jPanel_Cart.setLayout(jPanel_CartLayout);
        jPanel_CartLayout.setHorizontalGroup(
            jPanel_CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlCurrentlyInCart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_CartLayout.setVerticalGroup(
            jPanel_CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlCurrentlyInCart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Pig.setBackground(new java.awt.Color(102, 0, 51));

        jLabel_Image_Pig.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Image_Pig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Image_Pig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CowBrisket.png"))); // NOI18N

        Final_PigParts1.setForeground(new java.awt.Color(255, 255, 255));
        Final_PigParts1.setText("Parts: Brisket");

        jLabel_PigPrice1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PigPrice1.setText("Price:");

        jLabel_PigStockLeft1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_PigStockLeft1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PigStockLeft1.setText("Stocks Left:");

        jButton_Pig1.setText("Add to Cart");
        jButton_Pig1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Pig1ActionPerformed(evt);
            }
        });

        Final_PanelPig.setBackground(new java.awt.Color(255, 255, 255));

        Final_AmountOrder.setText("Amount of Order:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Final_PanelPigLayout = new javax.swing.GroupLayout(Final_PanelPig);
        Final_PanelPig.setLayout(Final_PanelPigLayout);
        Final_PanelPigLayout.setHorizontalGroup(
            Final_PanelPigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Final_PanelPigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Final_AmountOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addContainerGap())
        );
        Final_PanelPigLayout.setVerticalGroup(
            Final_PanelPigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Final_PanelPigLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(Final_PanelPigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Final_AmountOrder)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_PigLayout = new javax.swing.GroupLayout(jPanel_Pig);
        jPanel_Pig.setLayout(jPanel_PigLayout);
        jPanel_PigLayout.setHorizontalGroup(
            jPanel_PigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_PigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Final_PigParts1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_PigPrice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_PigStockLeft1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_PigLayout.createSequentialGroup()
                        .addComponent(jButton_Pig1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Final_PanelPig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Image_Pig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_PigLayout.setVerticalGroup(
            jPanel_PigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_Pig, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Final_PigParts1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_PigPrice1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_PigStockLeft1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Final_PanelPig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Pig1)
                .addGap(17, 17, 17))
        );

        jButton_MainPage.setFont(new java.awt.Font("Helvetica Rounded", 0, 12)); // NOI18N
        jButton_MainPage.setText("Main Page");
        jButton_MainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MainPageActionPerformed(evt);
            }
        });

        jPanel_Pig1.setBackground(new java.awt.Color(102, 0, 51));

        jLabel_Image_Pig1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Image_Pig1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Image_Pig1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CowRib.png"))); // NOI18N

        Final_PigParts3.setForeground(new java.awt.Color(255, 255, 255));
        Final_PigParts3.setText("Parts: Ribs");

        jLabel_PigPrice3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PigPrice3.setText("Price:");

        jLabel_PigStockLeft3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_PigStockLeft3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PigStockLeft3.setText("Stocks Left:");

        jButton_Pig3.setText("Add to Cart");
        jButton_Pig3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Pig3ActionPerformed(evt);
            }
        });

        Final_PanelPig1.setBackground(new java.awt.Color(255, 255, 255));

        Final_AmountOrder1.setText("Amount of Order:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Final_PanelPig1Layout = new javax.swing.GroupLayout(Final_PanelPig1);
        Final_PanelPig1.setLayout(Final_PanelPig1Layout);
        Final_PanelPig1Layout.setHorizontalGroup(
            Final_PanelPig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Final_PanelPig1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Final_AmountOrder1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addContainerGap())
        );
        Final_PanelPig1Layout.setVerticalGroup(
            Final_PanelPig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Final_PanelPig1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(Final_PanelPig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Final_AmountOrder1)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_Pig1Layout = new javax.swing.GroupLayout(jPanel_Pig1);
        jPanel_Pig1.setLayout(jPanel_Pig1Layout);
        jPanel_Pig1Layout.setHorizontalGroup(
            jPanel_Pig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Pig1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Pig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Final_PigParts3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_PigPrice3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_PigStockLeft3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_Pig1Layout.createSequentialGroup()
                        .addComponent(jButton_Pig3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Final_PanelPig1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Image_Pig1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_Pig1Layout.setVerticalGroup(
            jPanel_Pig1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Pig1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_Pig1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Final_PigParts3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_PigPrice3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_PigStockLeft3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Final_PanelPig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Pig3)
                .addGap(17, 17, 17))
        );

        jPanel_Pig2.setBackground(new java.awt.Color(102, 0, 51));

        jLabel_Image_Pig2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Image_Pig2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Image_Pig2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CowLoin.png"))); // NOI18N

        Final_PigParts2.setForeground(new java.awt.Color(255, 255, 255));
        Final_PigParts2.setText("Parts: Loin");

        jLabel_PigPrice2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PigPrice2.setText("Price:");

        jLabel_PigStockLeft2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_PigStockLeft2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PigStockLeft2.setText("Stocks Left:");

        jButton_Pig2.setText("Add to Cart");
        jButton_Pig2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Pig2ActionPerformed(evt);
            }
        });

        Final_PanelPig2.setBackground(new java.awt.Color(255, 255, 255));

        Final_AmountOrder2.setText("Amount of Order:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Final_PanelPig2Layout = new javax.swing.GroupLayout(Final_PanelPig2);
        Final_PanelPig2.setLayout(Final_PanelPig2Layout);
        Final_PanelPig2Layout.setHorizontalGroup(
            Final_PanelPig2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Final_PanelPig2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Final_AmountOrder2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addContainerGap())
        );
        Final_PanelPig2Layout.setVerticalGroup(
            Final_PanelPig2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Final_PanelPig2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(Final_PanelPig2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Final_AmountOrder2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_Pig2Layout = new javax.swing.GroupLayout(jPanel_Pig2);
        jPanel_Pig2.setLayout(jPanel_Pig2Layout);
        jPanel_Pig2Layout.setHorizontalGroup(
            jPanel_Pig2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Pig2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_Pig2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Final_PigParts2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_PigPrice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_PigStockLeft2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_Pig2Layout.createSequentialGroup()
                        .addComponent(jButton_Pig2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Final_PanelPig2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Image_Pig2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_Pig2Layout.setVerticalGroup(
            jPanel_Pig2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Pig2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_Pig2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Final_PigParts2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_PigPrice2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_PigStockLeft2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Final_PanelPig2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Pig2)
                .addGap(17, 17, 17))
        );

        jPanel_Cart1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel_Cart1.setAlignmentX(0.0F);
        jPanel_Cart1.setAlignmentY(0.0F);

        tlMoney.setFont(new java.awt.Font("Helvetica Light", 1, 12)); // NOI18N
        tlMoney.setText("Money: 00");

        javax.swing.GroupLayout jPanel_Cart1Layout = new javax.swing.GroupLayout(jPanel_Cart1);
        jPanel_Cart1.setLayout(jPanel_Cart1Layout);
        jPanel_Cart1Layout.setHorizontalGroup(
            jPanel_Cart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Cart1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlMoney)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Cart1Layout.setVerticalGroup(
            jPanel_Cart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Cart1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlMoney)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(45, Short.MAX_VALUE)
                        .addComponent(jPanel_Pig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_Cart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Pig2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_MainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_Pig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jPanel_Cart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Cart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_MainPage))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_Pig2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Pig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_Pig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Pig1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Pig1ActionPerformed
   // ORDER 1
          order1 = jTextField1.getText();
   try {
       
        if (!order1.isBlank()){
           if (!Character.isAlphabetic(Integer.parseInt(order1))) {
               if (Integer.parseInt(order1) <= Data.GetData(stocksline1)){
                   if (Data.GetUserMoney() >= Data.GetData(priceline1)){
                   
                        Data.SetUserOrder(order1, 4);
                        Data.UpdateStocks( order1, stocksline1);
                        int Money = Data.GetUserMoney() - Integer.parseInt(price1);
                        Data.SetUserMoney(Integer.toString(Money));
                   }
                   else {Data.NoMoneyLeft();}
               
               } else {Data.NoStocksLeft();}
             
            } else {Data.Incorrect();}
        }
        else {Data.Incorrect();}
        
        jLabel_PigStockLeft1.setText("Stocks Left: " + Data.GetData(stocksline1));
        tlCurrentlyInCart.setText("Currently in Cart: " + Integer.toString(Data.CurrentlyInCart()));
        tlMoney.setText("Money: " + Data.GetUserMoney());
        
    } catch (IOException ex) {}
 

    }//GEN-LAST:event_jButton_Pig1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton_MainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MainPageActionPerformed
        // TODO add your handling code here:
        MainPage.init();
        dispose();
    }//GEN-LAST:event_jButton_MainPageActionPerformed

    private void jButton_Pig3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Pig3ActionPerformed
        // ORDER 3
          order3 = jTextField3.getText();
   try {
       
        if (!order3.isBlank()){
           if (!Character.isAlphabetic(Integer.parseInt(order3))) {
               if (Integer.parseInt(order3) <= Data.GetData(stocksline3)){
                   if (Data.GetUserMoney() >= Data.GetData(priceline3)){
                   
                        Data.SetUserOrder(order3, 6);
                        Data.UpdateStocks( order3, stocksline3);
                        int Money = Data.GetUserMoney() - Integer.parseInt(price3);
                        Data.SetUserMoney(Integer.toString(Money));
                   }
                   else {Data.NoMoneyLeft();}
               
               } else {Data.NoStocksLeft();}
             
            } else {Data.Incorrect();}
        }
        else {Data.Incorrect();}
        
        jLabel_PigStockLeft3.setText("Stocks Left: " + Data.GetData(stocksline3));
        tlCurrentlyInCart.setText("Currently in Cart: " + Integer.toString(Data.CurrentlyInCart()));
        tlMoney.setText("Money: " + Data.GetUserMoney());
        
    } catch (IOException ex) {}
 

    }//GEN-LAST:event_jButton_Pig3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton_Pig2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Pig2ActionPerformed
// ORDER 2
          order2 = jTextField2.getText();
   try {
       
        if (!order2.isBlank()){
           if (!Character.isAlphabetic(Integer.parseInt(order2))) {
               if (Integer.parseInt(order2) <= Data.GetData(stocksline2)){
                   if (Data.GetUserMoney() >= Data.GetData(priceline2)){
                   
                        Data.SetUserOrder(order2, 5);
                        Data.UpdateStocks( order2, stocksline2);
                        int Money = Data.GetUserMoney() - Integer.parseInt(price2);
                        Data.SetUserMoney(Integer.toString(Money));
                   }
                   else {Data.NoMoneyLeft();}
               
               } else {Data.NoStocksLeft();}
             
            } else {Data.Incorrect();}
        }
        else {Data.Incorrect();}
        
        jLabel_PigStockLeft2.setText("Stocks Left: " + Data.GetData(stocksline2));
        tlCurrentlyInCart.setText("Currently in Cart: " + Integer.toString(Data.CurrentlyInCart()));
        tlMoney.setText("Money: " + Data.GetUserMoney());
        
    } catch (IOException ex) {}
 

    }//GEN-LAST:event_jButton_Pig2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void init() {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run()  {
                new CowPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Final_AmountOrder;
    private javax.swing.JLabel Final_AmountOrder1;
    private javax.swing.JLabel Final_AmountOrder2;
    private javax.swing.JPanel Final_PanelPig;
    private javax.swing.JPanel Final_PanelPig1;
    private javax.swing.JPanel Final_PanelPig2;
    private javax.swing.JLabel Final_PigParts1;
    private javax.swing.JLabel Final_PigParts2;
    private javax.swing.JLabel Final_PigParts3;
    private javax.swing.JButton jButton_MainPage;
    private javax.swing.JButton jButton_Pig1;
    private javax.swing.JButton jButton_Pig2;
    private javax.swing.JButton jButton_Pig3;
    private javax.swing.JLabel jLabel_Image_Pig;
    private javax.swing.JLabel jLabel_Image_Pig1;
    private javax.swing.JLabel jLabel_Image_Pig2;
    private javax.swing.JLabel jLabel_PigPrice1;
    private javax.swing.JLabel jLabel_PigPrice2;
    private javax.swing.JLabel jLabel_PigPrice3;
    private javax.swing.JLabel jLabel_PigStockLeft1;
    private javax.swing.JLabel jLabel_PigStockLeft2;
    private javax.swing.JLabel jLabel_PigStockLeft3;
    private javax.swing.JPanel jPanel_Cart;
    private javax.swing.JPanel jPanel_Cart1;
    private javax.swing.JPanel jPanel_Pig;
    private javax.swing.JPanel jPanel_Pig1;
    private javax.swing.JPanel jPanel_Pig2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel tlCurrentlyInCart;
    private javax.swing.JLabel tlMoney;
    // End of variables declaration//GEN-END:variables
}
