
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MainPage extends javax.swing.JFrame {
Data Data = new Data();
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        
        
    try {
        tlCurrentlyInCart.setText("Currently in Cart: " + Integer.toString(Data.CurrentlyInCart()));
        tlMoney.setText("Money: " + Data.GetUserMoney());
    } catch (IOException ex) {}
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Cart = new javax.swing.JPanel();
        tlCurrentlyInCart = new javax.swing.JLabel();
        jPanel_Category = new javax.swing.JPanel();
        jLabel_Categories = new javax.swing.JLabel();
        jPanel_Pig = new javax.swing.JPanel();
        jLabel_Image_Pig = new javax.swing.JLabel();
        jLabel_PigParts = new javax.swing.JLabel();
        jButton_Pig = new javax.swing.JButton();
        Final_Pig = new javax.swing.JLabel();
        jLabel_PigStockLeft2 = new javax.swing.JLabel();
        jLabel_PigStockLeft = new javax.swing.JLabel();
        jLabel_PigStockLeft1 = new javax.swing.JLabel();
        jPanel_Cow = new javax.swing.JPanel();
        jLabel_Image_Cow = new javax.swing.JLabel();
        jLabel_CowParts = new javax.swing.JLabel();
        jButton_Cow = new javax.swing.JButton();
        Final_Cow = new javax.swing.JLabel();
        jLabel_CowStockBelly = new javax.swing.JLabel();
        jLabel_CowStockLeg = new javax.swing.JLabel();
        jLabel_CowStockHead = new javax.swing.JLabel();
        jPanel_Chicken = new javax.swing.JPanel();
        jLabel_Image_Chicken = new javax.swing.JLabel();
        jLabel_ChickenParts = new javax.swing.JLabel();
        jButton_Chicken = new javax.swing.JButton();
        Final_Chicken = new javax.swing.JLabel();
        jLabel_ChickenStockBreast = new javax.swing.JLabel();
        jLabel_ChickenStockLeg = new javax.swing.JLabel();
        jLabel_ChickenStockWings = new javax.swing.JLabel();
        Print = new javax.swing.JButton();
        jPanel_Cart1 = new javax.swing.JPanel();
        tlMoney = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setFocusableWindowState(false);
        setFont(new java.awt.Font("Helvetica", 0, 12)); // NOI18N
        setResizable(false);

        jPanel_Cart.setBackground(new java.awt.Color(102, 0, 51));
        jPanel_Cart.setAlignmentX(0.0F);
        jPanel_Cart.setAlignmentY(0.0F);

        tlCurrentlyInCart.setForeground(new java.awt.Color(255, 255, 255));
        tlCurrentlyInCart.setText("Currently in Cart: 00");

        javax.swing.GroupLayout jPanel_CartLayout = new javax.swing.GroupLayout(jPanel_Cart);
        jPanel_Cart.setLayout(jPanel_CartLayout);
        jPanel_CartLayout.setHorizontalGroup(
            jPanel_CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlCurrentlyInCart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_CartLayout.setVerticalGroup(
            jPanel_CartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlCurrentlyInCart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_Category.setBackground(new java.awt.Color(102, 0, 51));

        jLabel_Categories.setFont(new java.awt.Font("Helvetica Rounded", 0, 12)); // NOI18N
        jLabel_Categories.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Categories.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Categories.setText("Categories of Meat");

        javax.swing.GroupLayout jPanel_CategoryLayout = new javax.swing.GroupLayout(jPanel_Category);
        jPanel_Category.setLayout(jPanel_CategoryLayout);
        jPanel_CategoryLayout.setHorizontalGroup(
            jPanel_CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CategoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Categories, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_CategoryLayout.setVerticalGroup(
            jPanel_CategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CategoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Categories, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel_Pig.setBackground(new java.awt.Color(102, 0, 51));

        jLabel_Image_Pig.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Image_Pig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Image_Pig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pig.png"))); // NOI18N

        jLabel_PigParts.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PigParts.setText("Parts in Stocks:");

        jButton_Pig.setText("Go to Pig Section");
        jButton_Pig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PigActionPerformed(evt);
            }
        });

        Final_Pig.setForeground(new java.awt.Color(255, 255, 255));
        Final_Pig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Final_Pig.setText("Pig");

        jLabel_PigStockLeft2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_PigStockLeft2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PigStockLeft2.setText("Belly:");

        jLabel_PigStockLeft.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_PigStockLeft.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PigStockLeft.setText("Leg:");

        jLabel_PigStockLeft1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_PigStockLeft1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PigStockLeft1.setText("Head:");

        javax.swing.GroupLayout jPanel_PigLayout = new javax.swing.GroupLayout(jPanel_Pig);
        jPanel_Pig.setLayout(jPanel_PigLayout);
        jPanel_PigLayout.setHorizontalGroup(
            jPanel_PigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PigLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_PigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_PigParts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Image_Pig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_PigLayout.createSequentialGroup()
                        .addComponent(jButton_Pig, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Final_Pig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_PigStockLeft2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_PigStockLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_PigStockLeft1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_PigLayout.setVerticalGroup(
            jPanel_PigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_Pig, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Final_Pig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_PigParts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_PigStockLeft2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_PigStockLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_PigStockLeft1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Pig)
                .addGap(17, 17, 17))
        );

        jPanel_Cow.setBackground(new java.awt.Color(102, 0, 51));

        jLabel_Image_Cow.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Image_Cow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Image_Cow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cow.png"))); // NOI18N

        jLabel_CowParts.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CowParts.setText("Parts in Stocks:");

        jButton_Cow.setText("Go to Cow Section");
        jButton_Cow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CowActionPerformed(evt);
            }
        });

        Final_Cow.setForeground(new java.awt.Color(255, 255, 255));
        Final_Cow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Final_Cow.setText("Cow");

        jLabel_CowStockBelly.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_CowStockBelly.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CowStockBelly.setText("Belly:");

        jLabel_CowStockLeg.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_CowStockLeg.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CowStockLeg.setText("Leg:");

        jLabel_CowStockHead.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_CowStockHead.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CowStockHead.setText("Head:");

        javax.swing.GroupLayout jPanel_CowLayout = new javax.swing.GroupLayout(jPanel_Cow);
        jPanel_Cow.setLayout(jPanel_CowLayout);
        jPanel_CowLayout.setHorizontalGroup(
            jPanel_CowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_CowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_CowParts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Image_Cow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_CowLayout.createSequentialGroup()
                        .addComponent(jButton_Cow, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Final_Cow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_CowStockBelly, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_CowStockLeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_CowStockHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_CowLayout.setVerticalGroup(
            jPanel_CowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_Cow, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Final_Cow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_CowParts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_CowStockBelly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_CowStockLeg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_CowStockHead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Cow)
                .addGap(17, 17, 17))
        );

        jPanel_Chicken.setBackground(new java.awt.Color(102, 0, 51));

        jLabel_Image_Chicken.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Image_Chicken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Image_Chicken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Chicken.png"))); // NOI18N

        jLabel_ChickenParts.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ChickenParts.setText("Parts in Stocks:");

        jButton_Chicken.setText("Go to Chicken Section");
        jButton_Chicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChickenActionPerformed(evt);
            }
        });

        Final_Chicken.setForeground(new java.awt.Color(255, 255, 255));
        Final_Chicken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Final_Chicken.setText("Chicken");

        jLabel_ChickenStockBreast.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_ChickenStockBreast.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ChickenStockBreast.setText("Breast:");

        jLabel_ChickenStockLeg.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_ChickenStockLeg.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ChickenStockLeg.setText("Leg:");

        jLabel_ChickenStockWings.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_ChickenStockWings.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ChickenStockWings.setText("Wings:");

        javax.swing.GroupLayout jPanel_ChickenLayout = new javax.swing.GroupLayout(jPanel_Chicken);
        jPanel_Chicken.setLayout(jPanel_ChickenLayout);
        jPanel_ChickenLayout.setHorizontalGroup(
            jPanel_ChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChickenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_ChickenParts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Image_Chicken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_ChickenLayout.createSequentialGroup()
                        .addComponent(jButton_Chicken, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Final_Chicken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_ChickenStockBreast, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_ChickenStockLeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_ChickenStockWings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_ChickenLayout.setVerticalGroup(
            jPanel_ChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChickenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image_Chicken, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Final_Chicken)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_ChickenParts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ChickenStockBreast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_ChickenStockLeg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_ChickenStockWings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Chicken)
                .addGap(17, 17, 17))
        );

        Print.setText("Print Receipt");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        jPanel_Cart1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel_Cart1.setAlignmentX(0.0F);
        jPanel_Cart1.setAlignmentY(0.0F);

        tlMoney.setFont(new java.awt.Font("Helvetica Light", 1, 12)); // NOI18N
        tlMoney.setText("Money: 00");

        javax.swing.GroupLayout jPanel_Cart1Layout = new javax.swing.GroupLayout(jPanel_Cart1);
        jPanel_Cart1.setLayout(jPanel_Cart1Layout);
        jPanel_Cart1Layout.setHorizontalGroup(
            jPanel_Cart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Cart1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlMoney)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_Cart1Layout.setVerticalGroup(
            jPanel_Cart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Cart1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tlMoney)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_Cart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99)
                .addComponent(jPanel_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_Cart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jPanel_Pig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jPanel_Chicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_Cow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel_Cart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Print)))
                    .addComponent(jPanel_Cart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Pig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel_Chicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel_Cow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_PigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PigActionPerformed
        // TODO add your handling code here:11
        PigPage.init(); //Go to Pig Section
        dispose(); //close this thingy
    }//GEN-LAST:event_jButton_PigActionPerformed

    private void jButton_ChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChickenActionPerformed
        // TODO add your handling code here:
        ChickenPage.init(); //Go to Chicken Section
        dispose(); //close this thingy
    }//GEN-LAST:event_jButton_ChickenActionPerformed

    private void jButton_CowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CowActionPerformed
        // TODO add your handling code here:
        CowPage.init(); //Go to Cow Section
        dispose(); //close this thingy
    }//GEN-LAST:event_jButton_CowActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
    try {
        // TODO add your handling code here:
        Data.PrintReceipt();
        Data.ReadReciept();
    } catch (IOException e) {}
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Final_Chicken;
    private javax.swing.JLabel Final_Cow;
    private javax.swing.JLabel Final_Pig;
    private javax.swing.JButton Print;
    private javax.swing.JButton jButton_Chicken;
    private javax.swing.JButton jButton_Cow;
    private javax.swing.JButton jButton_Pig;
    private javax.swing.JLabel jLabel_Categories;
    private javax.swing.JLabel jLabel_ChickenParts;
    private javax.swing.JLabel jLabel_ChickenStockBreast;
    private javax.swing.JLabel jLabel_ChickenStockLeg;
    private javax.swing.JLabel jLabel_ChickenStockWings;
    private javax.swing.JLabel jLabel_CowParts;
    private javax.swing.JLabel jLabel_CowStockBelly;
    private javax.swing.JLabel jLabel_CowStockHead;
    private javax.swing.JLabel jLabel_CowStockLeg;
    private javax.swing.JLabel jLabel_Image_Chicken;
    private javax.swing.JLabel jLabel_Image_Cow;
    private javax.swing.JLabel jLabel_Image_Pig;
    private javax.swing.JLabel jLabel_PigParts;
    private javax.swing.JLabel jLabel_PigStockLeft;
    private javax.swing.JLabel jLabel_PigStockLeft1;
    private javax.swing.JLabel jLabel_PigStockLeft2;
    private javax.swing.JPanel jPanel_Cart;
    private javax.swing.JPanel jPanel_Cart1;
    private javax.swing.JPanel jPanel_Category;
    private javax.swing.JPanel jPanel_Chicken;
    private javax.swing.JPanel jPanel_Cow;
    private javax.swing.JPanel jPanel_Pig;
    private javax.swing.JLabel tlCurrentlyInCart;
    private javax.swing.JLabel tlMoney;
    // End of variables declaration//GEN-END:variables
}
